 protected void cancel(Exception cause) throws Exception { } 