 public void testBug4860() throws Exception { testBug4138(); } 